backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/assets/portfolio"
public_folder: "/assets/portfolio"
publish_mode: editorial_workflow

# These lines should *not* be indented, directories named from root
collections:
  - label: "portfolio"
    name: "portfolio"
    folder: "src/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - label: "Description"
        name: "d2"
        widget: "list"
        field: {label: "Paragraph", name: "dPar", widget: "text"}
      - { label: "Disciplines", name: "disc", widget: "string" }
      - label: "Collaborators"
        name: "collabs2"
        widget: "list"
        field: {collapsed: "false", label: "Role(Name)", name: "collaber2", widget: "string"}
      - label: "Snippet Image" 
        name: "snipImgSet" 
        widget: "object"
        summary: 'snippet image settings'
        fields:
        - { label: "Image / Video Poster, only paste in the copied image URL, do not select it! URL should start with 'src'", name: "snipImg", widget: "image" }
        - { label: "Video?", name: "snipVidB", widget: "boolean", default: false }
        - { label: "Source path. Select an asset from the media assets, copy its path and paste it here. Only use MP4 in this slot.", name: "snipVidSource", widget: "string", required: false}
        - { label: "Video WebM source, more optimized but optional", name: "snipWebmSource", widget: "string", required: false }
        - { label: "Alt text (short description of the asset)", name: "snipAlt", widget: "string", default: "visual asset, needs alt text" }
      - label: "Featured Image" 
        name: "ftImgSet" 
        widget: "object"
        summary: 'featured image settings'
        fields:
        - { label: "Image / Video Poster, only paste in the copied image URL, do not select it! URL should start with 'src'", name: "ftImg", widget: "image" }
        - { label: "Video?", name: "ftVidB", widget: "boolean", default: false }
        - { label: "Source path. Select an asset from the media assets, copy its path and paste it here. Only use MP4 in this slot.", name: "ftVidSource", widget: "string", required: false }
        - { label: "Video WebM source path (more optimized but optional)", name: "ftWebmSource", widget: "string", required: false }
        - { label: "Alt text (short description of the asset)", name: "ftAlt", widget: "string", default: "visual asset, needs alt text" }
      - label: "Image Rows" 
        name: "images" 
        widget: "list"
        summary: 'Image Row'
        fields:
        - label: "Image Row" 
          name: "imgRow" 
          widget: "object"
          summary: 'Image Row'
          fields:
          - label: "Margin size"
            name: "mSize"
            widget: "select"
            default: ["small"]
            options: ["small", "large"]
          - label: "Layout"
            name: "layout"
            widget: "select"
            default: ["one-col"]
            options: ["one-col", "two-col-even", "two-col-right", "two-col-left", "three-col"]
          - label: "Image" 
            name: "imageRowContents" 
            widget: "list"
            summary: '{{fields.alt}}'
            fields:
            - { label: "Video?", name: "videoB", widget: "boolean", default: false }
            - { label: "Source path. Select an asset from the media assets, copy its path and paste it here. Only use MP4 formats for video.", name: "srcb", widget: "string" }
            - { label: "Video WebM source", name: "wmSrc", widget: "string", required: false }
            - { label: "Poster source if Video", name: "pSrc", widget: "string", default: "no" }
            - { label: "Alt text", name: "alt", widget: "string", default: "visual asset, needs alt text" }
  - label: "Site info"
    name: "site-info"
    folder: "src/info"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "list", default: ["infosrc"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Contact email address", name: "email", widget: "string" }
      - { label: "Instagram handle", name: "social", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }