backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/assets/portfolio"
public_folder: "/assets/portfolio"
publish_mode: editorial_workflow

# These lines should *not* be indented, directories named from root
collections:
  - label: "portfolio"
    name: "portfolio"
    folder: "src/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Disciplines", name: "disc", widget: "string" }
      - { label: "Collaborators", name: "collabs", widget: "string" }
      - { label: "Snippet Image", name: "snipImg", widget: "image" }
      - { label: "Snippet Image Alt Text", name: "snipImgAlt", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - label: "Image Rows" 
        name: "images" 
        widget: "list"
        summary: 'Image Row'
        fields:
        - label: "Image Row" 
          name: "imgRow" 
          widget: "object"
          summary: 'Image Row'
          fields:
          - label: "Margin size"
            name: "mSize"
            widget: "select"
            default: ["small"]
            options: ["small", "large"]
          - label: "Layout"
            name: "layout"
            widget: "select"
            default: ["one-col"]
            options: ["one-col", "two-col-even", "two-col-right", "two-col-left", "three-col"]
          - label: "Image" 
            name: "imageRowContents" 
            widget: "list"
            summary: '{{fields.alt}}'
            fields:
            - { label: "Video?", name: "videoB", widget: "boolean", default: false }
            - { label: "Source path. Select an asset from the media assets, copy its path and paste it here. Only use MP4 formats for video.", name: "srcb", widget: "string" }
            - { label: "Video WebM source", name: "wmSrc", widget: "string", required: false }
            - { label: "Poster source if Video", name: "pSrc", widget: "string", default: "no" }
            - { label: "Alt text", name: "alt", widget: "string", default: "visual asset, needs alt text" }
  - label: "Site info"
    name: "site-info"
    folder: "src/info"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "list", default: ["infosrc"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Contact email address", name: "email", widget: "string" }
      - { label: "Instagram handle", name: "social", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }